routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('kegiatan','KegiatanController');

app/Kegiatan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kegiatan extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.home');
    }
}

app/Http/Controllers/KegiatanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Kegiatan;
use App\User;


class KegiatanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kegiatans = Kegiatan::all();
        return view('user.kegiatan.show', compact('kegiatans'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.kegiatan.kegiatan');
               
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::all();
        $kegiatan = new Kegiatan;
            $kegiatan->kegiatan         = $request->kegiatan;
            $kegiatan->hasil            = $request->hasil;
            $kegiatan->tindaklanjut     = $request->tindaklanjut;
            $kegiatan->tanggal          = $request->tanggal;
            $kegiatan->user_id          = $request->user_id;
        $kegiatan->save();
        return redirect(route('kegiatan.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kegiatan = Kegiatan::where('id',$id)->first();
        return view('user.kegiatan.edit',compact('kegiatan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $kegiatan =  Kegiatan::find($id);
            $kegiatan->kegiatan         = $request->kegiatan;
            $kegiatan->hasil            = $request->hasil;
            $kegiatan->tindaklanjut     = $request->tindaklanjut;
            $kegiatan->tanggal          = $request->tanggal;
            $kegiatan->user_id          = $request->user_id;
        $kegiatan->update();
        return redirect(route('kegiatan.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        kegiatan::where('id',$id)->delete();
        return redirect()->back();
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/user/home.blade.php
@extends('user.layouts.app')

@section('main-content')  

@endsection

resources/views/user/kegiatan/edit.blade.php
@extends('user.layouts.app')

@section('main-content')  
<div id="jqueryvalidation" class="section">
  <div class="row">
    <div class="container">
      <div class="col s12 m12 l12">
        <div class="col s12">
          <div class="card-panel" style="margin-top: 37px;">
            <h4 class="header2">Tambah Kegiatan</h4>
            <div class="row">
              <form role="form" action="{{ route('kegiatan.update', $kegiatan->id) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}
                <div class="row">
                  <div class="input-field col s12">
                    <label for="kegiatan">Kegiatan:</label>
                    <input id="kegiatan" name="kegiatan" type="text" data-error=".errorTxt1" value="{{ $kegiatan->kegiatan }}">
                    <div class="errorTxt1"></div>
                  </div>
                  <div class="input-field col s12">
                    <label for="hasil">Hasil:</label>
                    <input id="hasil" type="text" name="hasil" data-error=".errorTxt2" value="{{ $kegiatan->hasil }}">
                    <div class="errorTxt2"></div>
                  </div>
                  <div class="input-field col s12">
                    <label for="tindaklanjut">Tindak Lanjut:</label>
                    <input id="tindaklanjut" type="text" name="tindaklanjut" data-error=".errorTxt3" value="{{ $kegiatan->tindaklanjut }}">
                    <div class="errorTxt3"></div>
                  </div>
                  <div class="input-field col s12">
                    <label for="tanggal">Tanggal:</label>
                    <input id="tanggal" class="datepicker" type="date" name="tanggal" data-error=".errorTxt4" value="{{ $kegiatan->tanggal }}">
                    <div class="errorTxt4"></div>
                  </div>

                  <input type="hidden"  name="user_id" value="{{ Auth::user()->id }} ">
                  
                </div>
                <div class="input-field col s12">
                  <button class="btn waves-effect waves-light right submit" type="submit" name="action">Submit
                    <i class="mdi-content-send right"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>  
    </div>
  </div>
</div>
</div>
</div>
</div>


@endsection

resources/views/user/kegiatan/kegiatan.blade.php
@extends('user.layouts.app')

@section('main-content')  
<div id="jqueryvalidation" class="section">
  <div class="row">
    <div class="container">
      <div class="col s12 m12 l12">
        <div class="col s12">
          <div class="card-panel" style="margin-top: 37px;">
            <h4 class="header2">Tambah Kegiatan</h4>
            <div class="row">
              <form role="form" action="{{ route('kegiatan.store') }}" method="POST">
                {{ csrf_field() }}
                <div class="row">
                  <div class="input-field col s12">
                    <label for="kegiatan">Kegiatan:</label>
                    <input id="kegiatan" name="kegiatan" type="text" data-error=".errorTxt1">
                    <div class="errorTxt1"></div>
                  </div>
                  <div class="input-field col s12">
                    <label for="hasil">Hasil:</label>
                    <input id="hasil" type="text" name="hasil" data-error=".errorTxt2">
                    <div class="errorTxt2"></div>
                  </div>
                  <div class="input-field col s12">
                    <label for="tindaklanjut">Tindak Lanjut:</label>
                    <input id="tindaklanjut" type="text" name="tindaklanjut" data-error=".errorTxt3">
                    <div class="errorTxt3"></div>
                  </div>
                  <div class="input-field col s12">
                    <label for="tanggal">Tanggal:</label>
                    <input id="tanggal" class="datepicker" type="date" name="tanggal" data-error=".errorTxt4">
                    <div class="errorTxt4"></div>
                  </div>

                  <input type="hidden"  name="user_id" value="{{ Auth::user()->id }} ">
                  
                </div>
                <div class="input-field col s12">
                  <button class="btn waves-effect waves-light right submit" type="submit" name="action">Submit
                    <i class="mdi-content-send right"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>  
    </div>
  </div>
</div>
</div>
</div>
</div>


@endsection

resources/views/user/kegiatan/show.blade.php
@extends('user.layouts.app')

@section('main-content')  
<div id="table-datatables">
  <h4 class="header center">Data Kegiatan</h4>
  <div class="row">
    <div class="col s12 m12">
      <table id="data-table-simple" class="responsive-table display" cellspacing="0">
        <thead>
          <tr>
            <th>ID</th>
            <th>Kegiatan</th>
            <th>Hasil</th>
            <th>Tindak Lanjut</th>
            <th>Tanggal</th>
            <th>Action</th>

          </tr>
        </thead>
        
        <tbody>

          @foreach($kegiatans as $kegiatan)
          @if ( Auth::user()->id == $kegiatan->user_id)
          <tr>
            <td>{{ $loop->index +1 }}</td>
            <td>{{ $kegiatan->kegiatan }}</td>
            <td>{{ $kegiatan->hasil }}</td>
            <td>{{ $kegiatan->tindaklanjut }}</td>
            <td>{{ $kegiatan->tanggal }}</td>
            <td><a href="{{ route('kegiatan.edit', $kegiatan->id) }}">Edit</a> | 
              <form method="POST" id="delete-form-{{ $kegiatan->id }}" action="{{ route('kegiatan.destroy', $kegiatan->id) }}" style="display: none">
                {{ csrf_field() }} {{ method_field('DELETE') }}
              </form>
              <a  type="button" onclick="
              if(confirm('Are you sure, want to delete {{ $kegiatan->kegiatan }}')) {
                event.preventDefault(); document.getElementById('delete-form-{{ $kegiatan->id }}').submit();
              } else {
                event.preventDefault();
              }
              ">Delete</a></td>

            </tr>
            @endif
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div> 



  @endsection

resources/views/user/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    @include('user.layouts.head')
</head>
<body>
    <div class="wrapper">
        @include('user.layouts.header')
        @include('user.layouts.sidebar')

        @section('main-content')
        @show
        

        @include('user.layouts.footer')
        
    </div>
</body>
</html>

resources/views/user/layouts/footer.blade.php
    <!-- jQuery Library -->
    <script type="text/javascript" src="{{asset('js/plugins/jquery-1.11.2.min.js')}}"></script>    
    <!--angularjs-->
    <script type="text/javascript" src="{{asset('js/plugins/angular.min.js')}}"></script>
    <!--materialize js-->
    <script type="text/javascript" src="{{asset('js/materialize.js')}}"></script>
    <!--prism -->
    <script type="text/javascript" src="{{asset('js/plugins/prism/prism.js')}}"></script>
    <!--scrollbar-->
    <script type="text/javascript" src="{{asset('js/plugins/perfect-scrollbar/perfect-scrollbar.min.js')}}"></script>
    <!-- chartist -->
    <script type="text/javascript" src="{{asset('js/plugins/chartist-js/chartist.min.js')}}"></script>
    
    <!-- chartist -->
    <script type="text/javascript" src="{{asset('js/plugins/jquery-validation/jquery.validate.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/plugins/jquery-validation/additional-methods.min.js')}}"></script>
    
    <script type="text/javascript" src="{{asset('js/plugins/data-tables/js/jquery.dataTables.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/plugins/data-tables/data-tables-script.js')}}"></script>
    <!--plugins.js - Some Specific JS codes for Plugin Settings-->
    <script type="text/javascript" src="{{asset('js/plugins.js')}}"></script>
    <!--custom-script.js - Add your own theme custom JS-->
    <script type="text/javascript" src="{{asset('js/custom-script.js')}}"></script>
    <script type='text/javascript'>
    $(window).load(function() {
        setTimeout(function() {
            Materialize.toast('<div id="card-alert" class="card green"><div class="card-content white-text"><p> SUCCESS to LOGIN</p></div>', 1500);
        }, 1500);
      });
    </script>

resources/views/user/layouts/head.blade.php
<link rel="stylesheet" type="text/css" href="{{asset('css/materialize.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('css/style.css')}}">
<!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
<link href="{{asset('js/plugins/perfect-scrollbar/perfect-scrollbar.css')}}" type="text/css" rel="stylesheet" media="screen,projection">
<link href="{{asset('js/plugins/jvectormap/jquery-jvectormap.css')}}" type="text/css" rel="stylesheet" media="screen,projection">
<link href="{{asset('js/plugins/chartist-js/chartist.min.css')}}" type="text/css" rel="stylesheet" media="screen,projection">
<link href="{{asset('js/plugins/data-tables/css/jquery.dataTables.min.css')}}" type="text/css" rel="stylesheet" media="screen,projection">

resources/views/user/layouts/header.blade.php
<header id="header" class="page-topbar">
        <!-- start header nav-->
        <div class="navbar-fixed">
            <nav class="navbar-color">
                <div class="nav-wrapper">
                    <ul class="left">                      
                      <li><h1 class="logo-wrapper"><a href="{{url('home')}}" class="brand-logo darken-1"><img src="images/materialize-logo.png" alt="materialize logo"></a> <span class="logo-text">Materialize</span></h1></li>
                    </ul><!-- 
                    <div class="header-search-wrapper hide-on-med-and-down">
                        <i class="mdi-action-search"></i>
                        <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize"/>
                    </div> -->
                    <ul class="right hide-on-med-and-down">
                        <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light translation-button"  data-activates="translation-dropdown"><img src="images/flag-icons/United-States.png" alt="USA" /></a>
                        </li>
                        <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
                        </li>
                        <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light notification-button" data-activates="notifications-dropdown"><i class="mdi-social-notifications"><small class="notification-badge">5</small></i>
                        
                        </a>
                        </li>                        
                        <li><a href="#" data-activates="chat-out" class="waves-effect waves-block waves-light chat-collapse"><i class="mdi-communication-chat"></i></a>
                        </li>
                    </ul>
                    <!-- translation-button -->
                    <ul id="translation-dropdown" class="dropdown-content">
                      <li>
                        <a href="#!"><img src="images/flag-icons/United-States.png" alt="English" />  <span class="language-select">English</span></a>
                      </li>
                      <li>
                        <a href="#!"><img src="images/flag-icons/France.png" alt="French" />  <span class="language-select">French</span></a>
                      </li>
                      <li>
                        <a href="#!"><img src="images/flag-icons/China.png" alt="Chinese" />  <span class="language-select">Chinese</span></a>
                      </li>
                      <li>
                        <a href="#!"><img src="images/flag-icons/Germany.png" alt="German" />  <span class="language-select">German</span></a>
                      </li>
                      
                    </ul>
                    <!-- notifications-dropdown -->
                    <ul id="notifications-dropdown" class="dropdown-content">
                      <li>
                        <h5>NOTIFICATIONS <span class="new badge">5</span></h5>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <a href="#!"><i class="mdi-action-add-shopping-cart"></i> A new order has been placed!</a>
                        <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
                      </li>
                      <li>
                        <a href="#!"><i class="mdi-action-stars"></i> Completed the task</a>
                        <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">3 days ago</time>
                      </li>
                      <li>
                        <a href="#!"><i class="mdi-action-settings"></i> Settings updated</a>
                        <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">4 days ago</time>
                      </li>
                      <li>
                        <a href="#!"><i class="mdi-editor-insert-invitation"></i> Director meeting started</a>
                        <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">6 days ago</time>
                      </li>
                      <li>
                        <a href="#!"><i class="mdi-action-trending-up"></i> Generate monthly report</a>
                        <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">1 week ago</time>
                      </li>
                    </ul>
                </div>
            </nav>
        </div>
        <!-- end header nav-->
    </header>
    <!-- END HEADER -->

resources/views/user/layouts/sidebar.blade.php
<!-- START MAIN -->
<div id="main">
        <!-- START WRAPPER -->
        <div class="wrapper">

            <!-- START LEFT SIDEBAR NAV-->
            <aside id="left-sidebar-nav">
                <ul id="slide-out" class="side-nav fixed leftside-navigation">
                <li class="user-details cyan darken-2">
                <div class="">
                    <div class="col col s4 m4 l4"></div>
                    <div class="col col s8 m8 l8">
                        <ul id="profile-dropdown" class="dropdown-content">
                            <li><a href="#"><i class="mdi-action-face-unlock"></i> Profile</a>
                            </li>
                            <li><a href="#"><i class="mdi-action-settings"></i> Settings</a>
                            </li>
                            <li><a href="#"><i class="mdi-communication-live-help"></i> Help</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="#"><i class="mdi-action-lock-outline"></i> Lock</a>
                            </li>
                            <li><a  href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                <i class="mdi-hardware-keyboard-tab"></i> Logout</a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                                </form>
                            </li>
                        </ul>
                        <a class="btn-flat dropdown-button waves-effect waves-light white-text profile-btn" href="#" data-activates="profile-dropdown">
                        {{ Auth::user()->name }}
                        <i class="mdi-navigation-arrow-drop-down right"></i></a>
                        <p class="user-roal">Administrator</p>
                    </div>
                </div>
                </li>
                <li class="bold active"><a href="{{url('home')}}" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Dashboard</a>
                </li>
                <li class="no-padding">
                    <ul class="collapsible collapsible-accordion">
                        <li class="bold"><a class="collapsible-header waves-effect waves-cyan"><i class="mdi-action-assignment"></i>Kegiatan</a>
                            <div class="collapsible-body">
                                <ul>
                                    <li><a href="{{route('kegiatan.create')}}">Tambah Kegiatan</a>
                                    </li>
                                    <li><a href="{{route('kegiatan.index')}}">Liat Kegiatan</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="no-padding">
                    <ul class="collapsible collapsible-accordion">
                        <li class="bold"><a class="collapsible-header waves-effect waves-cyan"><i class="mdi-image-brightness-4"></i>Amaliah</a>
                            <div class="collapsible-body">
                                <ul>
                                    <li><a href="layout-fullscreen.html">Tuliskan Amal</a>
                                    </li>
                                    <li><a href="layout-horizontal-menu.html">Lihat Amal</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
                <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>
            </aside>
            <!-- END LEFT SIDEBAR NAV-->

            <!-- //////////////////////////////////////////////////////////////////////////// -->